// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jszrtxpujtlflkgprkjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzenJ0eHB1anRsZmxrZ3Bya2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTM2OTgsImV4cCI6MjA2NDU4OTY5OH0.DkO3OAiaSFrJmUehmKBkMz6dQZrG0oq4v447FAtGWjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);